import "./globals.css";
import { NextAuthProvider } from "./nextAuthProvider";
import { RecoilProvider } from "./recoilRoot";
import { ReactQueryClientProvider } from "./reactQueryClient";

export const metadata = {
  title: "Bibot | 가상 결제 서비스",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RecoilProvider>
          <ReactQueryClientProvider>
            <NextAuthProvider>{children}</NextAuthProvider>
          </ReactQueryClientProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}
